//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirportTimeTable
    {
        public int ID { get; set; }
        public int AirlineID { get; set; }
        public int CodeID { get; set; }
        public int CityID { get; set; }
        public int TermID { get; set; }
    
        public virtual Airlines Airline { get; set; }
        public virtual AirportCode AirportCode { get; set; }
        public virtual Cities City { get; set; }
        public virtual Terminals Terminal { get; set; }
    }
}
