//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirportDB : DbContext
    {
        public AirportDB()
            : base("name=AirportDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airlines> Airlines1 { get; set; }
        public virtual DbSet<AirportCode> AirportCodes { get; set; }
        public virtual DbSet<AirportTimeTable> AirportTimeTables { get; set; }
        public virtual DbSet<Cities> Cities1 { get; set; }
        public virtual DbSet<Terminals> Terminals1 { get; set; }
    }
}
